### ISSUE TITLE
[issue] Debug message pinged to console every second

### ISSUE THREAD

**Issue by PalaNolho** [hktrpg/foundryVTT_game_time_clock#6]
The module is pinging some debug info to the console every second.
This is very annoying specially when we are trying to debug other stuff or use the console.

![image](https://user-images.githubusercontent.com/6009914/123244325-b97f8300-d4db-11eb-816f-396e28964575.png)

This seems to happen when both **_Game time clock_** AND **_Loud Whispers_** modules are active at the same time...
was not able to understand why
Thanks

**Comment by zeteticl** [comment]
You are in debug mode, so you got this debug message.
Just turn off debug mode

**Comment by PalaNolho** [comment]
where ? I checked that option but don't see it anywhere

![image](https://user-images.githubusercontent.com/6009914/123250286-cacb8e00-d4e1-11eb-8083-133e0859fd56.png)

**Comment by zeteticl** [comment]
CONFIG.debug.hooks = false

**Comment by PalaNolho** [comment]
ok that sorted it.
My question is how has this been activated if I didn't do it manually nor using any config :S

**Comment by zeteticl** [comment]
which system(character sheet) you are using?

**Comment by PalaNolho** [comment]
tidy5e sheet

**Comment by zeteticl** [comment]
some sheet have debug  setting, so....

**Comment by PalaNolho** [comment]
but as you see I don't have any sheet active. The test above was tested only with those 2 modules active

**Comment by zeteticl** [comment]
https://gitlab.com/n3dst4/louder-whispers/-/blob/main/module/louder-whispers.js#L77

louder-whispers.js would turn on the debug mode.
So, uninstall louder-whispers or game_time_clock
