### ISSUE TITLE
Constant Refreshing of the Sidebar causes issues

### ISSUE THREAD

**Issue by revilowaldow** [hktrpg/foundryVTT_game_time_clock#7]
Constantly refreshing the sidebar means a small image from another module (FX master) which is located there is constantly gettign reloaded causing issues

![image](https://user-images.githubusercontent.com/52298102/125514182-69c3d1e6-8956-4d7b-9262-1487b2acfd61.png)

**Comment by zeteticl** [comment]
![image](https://user-images.githubusercontent.com/23254376/125592600-547188aa-f919-4651-a56a-3cba9123ccd0.png)
I have enabled TIME CLOCK and FX MASTER,
But it can’t reproduce your problem, so there should be a third MOD to interfere
