### ISSUE TITLE
Forien's Copy Environment not working, when using Game Time Clock

### ISSUE THREAD

**Issue by marcstraube** [hktrpg/foundryVTT_game_time_clock#8]
FoundryVtt: 9.242
Game Time Clock: 1.2.2
Forien's Copy Environment: 2.0.7 (https://github.com/League-of-Foundry-Developers/foundryvtt-forien-copy-environment)

When using Game Time Clock, I can't export or import settings with Forien's Copy Environment.

**Comment by zeteticl** [comment]
Fixed in v1.3.2 
You can update on FVTT :D

**Comment by marcstraube** [comment]
Now everything works as expected! Thank you!
